
[profile.release]
#debug = true
lto = "fat"
codegen-units = 1

[workspace]
resolver = "2"
members = [
    "creature-creator",
    "creature-creator-renderer",
    "creature-creator-metal-renderer"
]
